const os = require('os')
console.log(os.arch())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.freemem())
console.log(os.totalmem())
console.log(os.platform())
console.log(os.cpus())
